### PR TITLE
feat(deps): remove dependency on `pytest-asyncio`

### PR DESCRIPTION
**Pull request by YaraslauZhylko**
Remove dependency on `pytest-asyncio` that is not used by the library in any way.

Also add formal support for Python 3.10, 3.11, 3.12, and 3.13.

### CODE REVIEW

**Comment by YaraslauZhylko** [comment]
@pheanex Not sure how you lock the dependencies (what `poetry` version) or how you do releases.
So please let me know if I need to adjust anything.

**Comment by pheanex** [comment]
Hey, thanks. That is great. For poetry I guess you should be able to use anything poetry>=0.12 and you can just do a `poetry lock` to update the lockfile

**Comment by YaraslauZhylko** [comment]
I did exactly this.

But my `poetry` is at v1.8.4.
And the generated `poetry.lock` is much different form the one you had.
So I assumed that you use a lower version that might not be compatible with v1.8.4 style.

Other than that, are we ready to merge?

**Comment by pheanex** [comment]
Okay, thank you. Sure. let's merge this and I'll take care of the lock-file :+1:

**Pull request merged**
